<a href="https://colab.research.google.com/github/itsRajatkumar/MachineLearning/blob/main/01MLPythonBasics1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Python Basics

basic operation


In [26]:
def sum(a=0,b=0,c=0):
    return a+b+c

s1=sum(4,8,6)
print(s1)
s1=sum(4,8)
print(s1)
s1=sum(4)
print(s1)
s1=sum(c=44)
print(s1)

18
12
4
44


In [27]:
def sum2(a,b,*more):
    ans=a+b
    for i in more:
        ans+=i
    return ans

s=sum2(45,8,9,6,5,3,5,2,4,5,8,5,8)
print(s)

113


In [28]:
def func(a,b):
    return a+b,a-b,a*b,a/b,a%b

a1,a2,a3,a4,a5=func(45,85)
ans=func(45,85)
print(ans)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

(130, -40, 3825, 0.5294117647058824, 45)
130
-40
3825
0.5294117647058824
45


In [29]:
a=[i for i in range(1,11,3) ]
print(a)

[1, 4, 7, 10]


In [30]:
print(a[2])

7


String

In [31]:
string="a b c d e f "
s=string.strip().split(" ")
print(s)
l=[int(i) for i in input().strip().split(" ")]
print(l)


['a', 'b', 'c', 'd', 'e', 'f']
1
[1]


List Operation

In [32]:
l=[8,9,5,7,5,6,2,3,5,4,8,9]
print(l)

l.append(10)
print(l)

l.insert(0,45)
print(l)

l.pop()
print(l)

l.pop(7)
print(l)

l.remove(6)
print(l)

del l[0]
print(l)

del l[2:5]
print(l)

[8, 9, 5, 7, 5, 6, 2, 3, 5, 4, 8, 9]
[8, 9, 5, 7, 5, 6, 2, 3, 5, 4, 8, 9, 10]
[45, 8, 9, 5, 7, 5, 6, 2, 3, 5, 4, 8, 9, 10]
[45, 8, 9, 5, 7, 5, 6, 2, 3, 5, 4, 8, 9]
[45, 8, 9, 5, 7, 5, 6, 3, 5, 4, 8, 9]
[45, 8, 9, 5, 7, 5, 3, 5, 4, 8, 9]
[8, 9, 5, 7, 5, 3, 5, 4, 8, 9]
[8, 9, 3, 5, 4, 8, 9]


In [33]:
l=[8,9,5,7,5,6,2,3,5,4,8,9]
print(l)
l.reverse()
print(l)

l.sort()
print(l)

print(l.count(5))

print(l.index(8))

a= 48 in l
print(a)


[8, 9, 5, 7, 5, 6, 2, 3, 5, 4, 8, 9]
[9, 8, 4, 5, 3, 2, 6, 5, 7, 5, 9, 8]
[2, 3, 4, 5, 5, 5, 6, 7, 8, 8, 9, 9]
3
8
False


Bubble sort

In [34]:
l=[int(i) for i in input().strip().split(" ")]
n=len(l)
for j in range(n-1):
    for i in range(0,n-1-j):
        if( l[i] > l[i+1]):
            temp=l[i]
            l[i]=l[i+1]
            l[i+1]=temp

print(l)

3 5 7 5 34 2 4 66 24 2
[2, 2, 3, 4, 5, 5, 7, 24, 34, 66]


Dictionary

In [35]:
d={}
d1={}
print(d==d1)
d['a']=34
print(d)

d[4]=38
print(d)

d['d']=85
print(d)

d['b']=65
print(d)

for i in d:
    print(i,end=":")
    print(d[i])

del d[4]
print(d)
print(d==d1)
print('a' in d)


True
{'a': 34}
{'a': 34, 4: 38}
{'a': 34, 4: 38, 'd': 85}
{'a': 34, 4: 38, 'd': 85, 'b': 65}
a:34
4:38
d:85
b:65
{'a': 34, 'd': 85, 'b': 65}
False
True


2D List

In [36]:
l=[[2,4,5],[5,7,8],[9,8,7]]
print(l)

print(l[0])

print(l[0][1])

l1=[[i for i in range(5)] for j in range(5)]
print(l1)

str=input("Enter Size of Array: ").strip().split("*")
n=int(str[0])
m=int(str[1])

l=[int(i) for i in input().strip().split(" ")]
out=[]
for i in range(n):
    out.append([])
    for j in range(m):
        out[i].append(l[i*m+j])

print(out)

[[2, 4, 5], [5, 7, 8], [9, 8, 7]]
[2, 4, 5]
4
[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
Enter Size of Array: 3*3
1 2 3 4 5 6 7 8 9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Wave Printing

In [37]:
n=len(out)
m=len(out[0])
for j in range(m):
    if j%2==0 :
        for i in range(n):
            print(out[i][j],end=(" "))
    else:
        for i in range(n-1,-1,-1):
            print(out[i][j],end=(" "))

1 4 7 8 5 2 3 6 9 

Numpy Module


In [38]:
import numpy as np
import math
l=np.array([1,2,3,4,5])
print(l)
print(l.dtype)

[1 2 3 4 5]
int64


NP Zeros And Once Module

In [39]:
arr1=np.zeros(9)
arr2=np.ones(9,int)

print(arr1)
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1]


Multi dimantional arrays

In [40]:
# 2D Arrays
arr3=np.zeros((3,3))
arr4=np.ones((3,3))

print(arr3)
print()
print()
print()
print(arr4)

print()
print()
print()

# 3D Arrays
arr5=np.zeros((3,3,2))
arr6=np.ones((3,3,2))

print(arr5)
print()
print()
print()
print(arr6)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
print(arr5.shape)
print(arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]



[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(9,)
(9,)
(3, 3)
(3, 3)
(3, 3, 2)
(3, 3, 2)


Numpy Operation

In [41]:
a=np.array([2,4,6])
b=np.array([1,3,5])

print(a+2)
print(a)
print(a*2)
print()
print(b+2)
print(b)
print(b*2)

print()
print(a.mean())
print(b.mean())

print()
print(a.sum())
print(b.sum())

[4 6 8]
[2 4 6]
[ 4  8 12]

[3 5 7]
[1 3 5]
[ 2  6 10]

4.0
3.0

12
9


Sqrt( (x1-x2)^2+(y1-y2)^2)


In [42]:
a=np.array([1,2,3])
b=np.array([4,5,6])
d=((a-b)**2).sum()
ans= math.sqrt(d)
print(ans)

5.196152422706632


E(Xi-Xmean)^2

In [43]:
x=np.array([9,8,7,5,6,4,2,3,1])
ans1=((x-x.mean())**2).sum()
print(ans1)

60.0


Dot(.) Product of Vectors

In [44]:
a=np.array([1,2,3])
b=np.array([4,5,6])
ans2=a.dot(b)
print(ans2)

32
